# Generated by Django 6.1 on 2026-08-17 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilbusqueda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('razones', models.JSONField(default=list)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='vacantes.perfilbusqueda')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-puntuacion'],
                'unique_together': {('vacante', 'perfil')},
            },
        ),
    ]
