# Generated by Django 6.1 on 2026-08-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_perfilbusqueda_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='vacantes.perfilbusqueda')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='vacantes.vacante')),
            ],
            options={
                'ordering': ['-creada'],
                'unique_together': {('vacante', 'perfil')},
            },
        ),
    ]
